# Generated by Django 3.0.3 on 2020-05-17 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200517_2321'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='instagram_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
