# Generated by Django 3.0.3 on 2020-05-05 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Arbonne', '0002_product_pub_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='product_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
