# Generated by Django 3.0.3 on 2020-05-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arbonne', '0006_analytics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytics',
            name='hits',
            field=models.IntegerField(default=0),
        ),
    ]
