# Generated by Django 3.0.3 on 2020-05-10 13:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Arbonne', '0010_auto_20200508_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 10, 13, 21, 25, 654382, tzinfo=utc)),
        ),
    ]
