# Generated by Django 3.0.3 on 2020-05-14 22:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Arbonne', '0011_auto_20200510_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='analytics',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 14, 22, 47, 13, 987142, tzinfo=utc)),
        ),
    ]
