# Generated by Django 3.0.3 on 2020-05-14 23:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Arbonne', '0013_auto_20200514_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 14, 23, 2, 55, 794522, tzinfo=utc)),
        ),
    ]
