# Generated by Django 3.0.3 on 2020-05-15 16:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Arbonne', '0016_auto_20200515_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytics',
            name='last_hit',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 15, 16, 52, 43, 660715, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hit',
            name='dateOfHit',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 15, 16, 52, 43, 660715, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hit',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 15, 16, 52, 43, 659717, tzinfo=utc)),
        ),
    ]
