# Generated by Django 3.0.3 on 2020-05-16 19:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Arbonne', '0017_auto_20200515_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytics',
            name='last_hit',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 16, 19, 42, 39, 494856, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='hit',
            name='dateOfHit',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 16, 19, 42, 39, 495852, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 16, 19, 42, 39, 494856, tzinfo=utc)),
        ),
    ]
