# Generated by Django 3.0.3 on 2020-05-16 19:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Arbonne', '0018_auto_20200516_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytics',
            name='last_hit',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='hit',
            name='dateOfHit',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
