# Generated by Django 3.0.3 on 2020-05-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arbonne', '0020_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image_url',
            field=models.CharField(max_length=1000),
        ),
    ]
